README.md
Fixing up a link in the README that didn't have `https://` in front of it.  
Hopefully non-controversial 😄
=> Little link fix

guides/basic-use/index.md
Only a few changes (the current text is good):
- Replaced 'may need' with 'we recommend'
- Updated synced 'missing watchman' message, to make this page show up in google results (https://github.com/chrmod/watch-detector/blob/master/lib/index.js#L256)
There are a few more things mentioned in the [old docs](https://ember-cli.com/user-guide/#watchman), but I'm not sure if they're worth moving over, they seem like pretty auxiliary things. If included, it would be neat to fold them into a details/summary block (if the docs site support that).
```
<details><summary>Debugging & Advanced</summary></details>
```
=> Improve watchman docs

guides/basic-use/index.md, guides/reference/windows.md
For #3 
Unedited except to make sure things work. Only new text is in index.md.
Update: Now edited in response to comments.
=> Port over Windows support

guides/reference/dev-tools.md
Initial port of Editor configuration with some minor formatting changes.
For https://github.com/ember-learn/cli-guides-source/issues/3
=> Port over Editors

README.md
Changed ```link the `ember-cli-guides-source` repository...``` to ```link the `cli-guides-source` repository```
=> Fixed name of repo in README for Local Development

guides/basic-use/upgrading.md
Initial commit of porting the app upgrade process.  I've included an example and a hint on how to recover from a bad upgrade.
What do you want to include for upgrading an addon?
=> Port over upgrading

guides/reference/common-issues.md
Add common issues markdown from ember-cli.com
-  Addressing issue [#3](https://github.com/ember-learn/cli-guides-source/issues/3), item 10, "Port over Common Issues. Mostly copy and paste from this source code"
-  Converted the markdown file found here: [https://raw.githubusercontent.com/ember-cli/ember-cli.github.io/master/_posts/2013-04-03-common-issues.md](https://raw.githubusercontent.com/ember-cli/ember-cli.github.io/master/_posts/2013-04-03-common-issues.md)
-  Update internal link to the Windows Support section
=> Common issues transfer

guides/advanced-use/blueprints.md
- 'addons' used when it should have been blueprints
- a few more back tics
- clarified `install` hook for use in advanced blueprints
=> wrong term used 'addons` -> `blueprints`

guides/index.md
Previously "forums and chat" here linked to the /learn/ page, but that page doesn't reference the forums and chat. It seems best to link to the /community/ page as we do in the previous section.
=> Correct "forums and chat" link

guides/basic-use/cli-commands.md, guides/index.md
Previously it was written at different places as "EmberObserver", "Ember Observer", and "EmberObserver.com". This PR makes the usages consistent.
I also change an "at" to "on" because "at EmberObserver.com" seems to make sense for a domain name, but when the ".com" is removed "on Ember Observer" seems to make more sense. And there are other places in the guides where we say "on Ember Observer".
We could standardize on another way of writing the term or even leave in exceptions if there's good reason; this PR would be a good place to discuss. Here are my thoughts:
- "Ember Observer" should be preferred over "EmberObserver" because the former is how emberobserver.com writes the name
- I don't see too much extra benefit of including ".com" in all uses of the name, or even in a single one to …
=> Write 'Ember Observer' consistently

guides/basic-use/cli-commands.md
Although "SASS" is an acronym, Wikipedia shows that it is normally written as "Sass". Elsewhere in the guides we write it that way; this updates the commands page with matching capitalization.
=> Normalize capitalization of "Sass"

guides/basic-use/cli-commands.md
Previously the text said the CLI "will rerender as files change." This threw me off a bit because usually "rendering" refers to what the browser does, but here we were saying that the CLI rendered. More precisely, the CLI makes the browser reload our app. I think this new phrasing is more precise without sacrificing clarity.
=> Reword description of live reload

guides/writing-addons/documenting.md
I propose adding a section on `CONTRIBUTING.md` since with the merge of https://github.com/ember-cli/ember-cli/pull/8203 a newly generated addon will now contain a `CONTRIBUTING.md` with installation instructions.
Note: This feature is merged but not released yet.
=> Add section on CONTRIBUTING.md

.travis.yml
As noded in https://github.com/ember-learn/cli-guides/issues/61, we should upgrade to Node 8. This matches what is done in the main guides so I expect it to work here too for our CI.
=> Change travis.yml to use Node 8 like the ember.js guides

guides/writing-addons/intro-tutorial.md
Replace <addon-name> to <component-name> in handlebar templates for component rendering.
=> Update component name in handlebar templates.

.local.dic, guides/pages.yml, guides/writing-addons/addon-dependencies.md
I want the partial `package.json` example to be from an existing addon that is simple enough to reason about.  ember-cli-babel is included by default, but would like a couple more.
I haven't spent much time looking but haven't found anything that I'd like to use - looking for suggestions
Resolves #98
=> Added section for addon dependencies

guides/writing-addons/intro-tutorial.md
The example's CSS file was named `app/styles/my-addon-name.css` but the import example was `@import 'our-addon-name.css'`, making the example hard to understand.
There was also a typo in a sample path
This PR originates from the discussion in #95, and fixes typos made in #101
=> Fix typo in filename reference and fix incoherence in examples

guides/advanced-use/blueprints.md
Adds second underscore wrapping token variable names in prose text.
Fixes incorrect file name reference in Template Variables section
=> Minor fix in token names + file name reference inconsistency

.alexrc, .local.dic, CONTRIBUTING.md, guides/pages.yml, guides/writing-addons/deprecations.md, package-lock.json, package.json
I just learned how to do this! I would love feedback on anything that is missing or could be explained better.
=> create a deprecations writing guide

.local.dic, guides/appendix/configuration.md, guides/pages.yml
Info on `.ember-cli` configuration wasn't copied over from old cli guides.  After publishing, I'll do another PR to link back here were it's mentioned in the [Ember guides](https://guides.emberjs.com/release/configuring-ember/configuring-ember-cli/)
=> Add section on .ember-cli configuration

app/styles/app.css, guides/advanced-use/asset-compilation.md, guides/basic-use/folder-layout.md, guides/pages.yml
Copy and updated from original guides.  Copied some text from the tutorial so language matched when possible.
This might be an appendix item but it's documented early in the old guides and is fundamental knowledge when developing an Ember app.
Links in tables don't show in the generated html.  I couldn't figure out the specific CSS to make it work so it needs to be added to `guidemaker-ember-template`
=> Add project folder layout

guides/basic-use/upgrading.md
Incorrect id in `Managing major upgrades` link, updates so link works as expected.
=> Fix internal page link

.local.dic, guides/advanced-use/project-layouts.md
I fixed a few typos and removed reference to `app/resolver.js` (this file is no longer present in Octane apps?).
Link to website: https://cli.emberjs.com/release/advanced-use/project-layouts/
=> Updated the Project Layouts section

guides/basic-use/index.md
We are removing the "installing" page from the Ember Guides, and the one thing it had that the CLI guides was missing was listing git as a dependency.
=> Add git to list of prerequisites

guides/basic-use/cli-commands.md
=> Updates info about component generator after octane release

guides/index.md
Now that Ember Auto Import is a default, we can say that 'it just works'
(I used Highcharts as the example because I've used it before and I know it works, but can be changed to any other example, or can remove the example too)
=> Update reference about importing npm packages

guides/pages.yml, guides/writing-addons/custom-commands.md
Closes #117.
cc @rwjblue this can probably be a lot better, but I lifted from your issue. Let me know if there's anything vital that can be added. 
Personally, I think custom commands shouldn't even be possible, we should just point to npm run-script, but it's already public API, so that's a separate topic
=> Document how to create custom commands

guides/basic-use/assets-and-dependencies.md, guides/basic-use/cli-commands.md
Setting `"yarn": true` in `.ember-cli` is undocumented. This adds some documentation about it.
=> Add info about yarn by default

guides/appendix/dev-tools.md, guides/basic-use/cli-commands.md
@jenweber is this what you had in mind for #124? 
I don't see any other references to "ajax" in the markdown files.
=> Replace 'ajax' with 'network'

.local.dic, guides/advanced-use/build-targets.md, guides/pages.yml
This is copied from https://guides.emberjs.com/release/configuring-ember/build-targets/
Closes #159. 
Once merged, the Ember Guides  should link to this page. That PR is here: https://github.com/ember-learn/guides-source/pull/1417
=> Move Build Targets page to CLI guides

guides/advanced-use/asset-compilation.md
The configuration mentioned here is outdated and doesn't work anymore.
Based on https://github.com/babel/ember-cli-babel/issues/355
=> Update outdated reference to ember-cli-babel configuration

guides/index.md
I was reviewing what we mention in the CLI Guides with regards to the folder structure for an in-repo addon. On the long horizon, I'd like to document the colocated folder structure in Octane (this pertains to the issue https://github.com/ember-learn/cli-guides/issues/135).
As I review each section, if it's okay with the team, I'd like to update the section by simplifying the writing (the grammar). For example, in this PR, I preferred 2 short sentences instead of 1 joined by an "and" or a "which." I'm hoping that the result is a writing that is easier to parse and feels conversational when read out aloud.
=> Updated Introduction by simplifying the writing

guides/writing-addons/index.md
`ember addon` is not a common command. This commit links to the command's available options for easier navigation.
=> Ember addons: link to commands reference

.local.dic, guides/advanced-use/cli-commands-reference.md
This PR attempts to add additional CLI information for each `ember generate` blueprint provided by default. The blueprints are the following:
- ember-source
- acceptance-test
- component
- component-addon
- component-class
- component-class-addon
- component-test
- controller
- controller-test
- helper
- helper-test
- initializer
- initializer-addon
- initializer-test
- instance-initializer
- instance-initializer-addon
- instance-initializer-test
- mixin
- mixin-test
- route
- route-addon
- route-test
- service
- service-test
- template
- util
- util-test
- ember-data
- adapter
- adapter-test
- model
- model-test
- serializer
- serializer-test
- transform
- transform-test
- ember-cli
- addon
- addon-import
- app
- blueprint
- http-mock
- http-proxy
- in-repo-addon
- lib
- server
- …
=> add ember generate blueprints to cli reference

guides/basic-use/cli-commands.md
Removed `For example, components must always have a dash in their names.` as this is not the case anymore.
=> Remove dash requirement for component names

guides/advanced-use/asset-compilation.md, guides/advanced-use/index.md
`ember-cli-terser` replaced `ember-cli-uglify` in the 3.21.1 blueprint.
Closes #216
=> Update the documentation about JS minification

guides/advanced-use/blueprints.md
`ember help generate foo` no longer shows this, unless I'm overlooking something.
=> Update ember help generate output documentation

.local.dic, guides/advanced-use/asset-compilation.md
The previous url linked to a repo that's archived.
=> Update babel-preset-env options docs url

guides/writing-addons/in-repo-addons.md
The https://cli.emberjs.com/release/writing-addons/in-repo-addons/#usingtemplateswithaninrepoaddon documentation lists `babel-plugin-htmlbars-inline-precompile` and `ember-cli-htmlbars-inline-precompile` as required dependencies, but they are no longer individually required.
`babel-plugin-htmlbars-inline-precompile` is a(n included) dependency of `ember-cli-htmlbars` (https://github.com/ember-cli/ember-cli-htmlbars/blob/master/package.json#L37)
`ember-cli-htmlbars-inline-precompile` is also a(n included) dependency of `ember-cli-htmlbars` (https://github.com/ember-cli/ember-cli-htmlbars-inline-precompile)
=> Remove individually-listed required packages that are (now) dependencies of others in the list

guides/writing-addons/index.md
File name typo error fixed for environment.js
=> File name typo change enviroment.js to environment.js

guides/advanced-use/blueprints.md, guides/advanced-use/cli-commands-reference.md
The [`--test-type` option is being removed in ember-source](https://github.com/emberjs/ember.js/pull/19808), so this PR updates the guides to match that change.
=> Remove the `--test-type` option from the helper-test blueprint

guides/advanced-use/debugging.md, guides/appendix/dev-tools.md, guides/basic-use/assets-and-dependencies.md, guides/writing-addons/addon-blueprints.md
Since the [Bower RFC implementation](https://github.com/ember-cli/ember-cli/pull/9707) has been merged (I assume it will be part of the upcoming `v4.2` release), I think we can start removing references to Bower from the guides?
=> Remove references to Bower

guides/writing-addons/index.md, guides/writing-addons/intro-tutorial.md
=> small typo in doc

.local.dic, guides/appendix/live-reload.md, guides/appendix/tailwind.md, guides/pages.yml
Resolves: https://github.com/ember-learn/cli-guides/issues/244
=> Add tailwind appendix

guides/appendix/live-reload.md
Addresses https://github.com/ember-learn/cli-guides/pull/245#issuecomment-1111772789.
- `autoprefixer` and `postcss` are only needed if you include `tailwindcss` as a PostCSS plugin
- Added the `--minify` flag to the `tailwind:build` script, since this is used for creating a production build
=> Update Tailwind appendix

guides/basic-use/deploying.md
The official ember tutorial no longer has a section on how to deploy Ember (closes #257)
=> Remove reference to deleted deployment tutorial

package-lock.json
terser
shell-quote
One of these upgrades caused the root URL to show a blank screen. The problems with the upgrades were masked by a re-deploy of an earlier commit about month ago, but then the problem resurfaced when a recent commit was made and auto-deployed.
=> Revert some breaking package updates

guides/advanced-use/debugging.md, guides/advanced-use/index.md, guides/advanced-use/stylesheets.md, guides/basic-use/folder-layout.md
I think this should suffice for now.
Closes https://github.com/ember-learn/cli-guides/issues/283.
=> Replace dead Broccoli links

.local.dic, guides/advanced-use/cli-commands-reference.md, guides/advanced-use/debugging.md, guides/appendix/configuration.md, guides/basic-use/assets-and-dependencies.md, guides/basic-use/cli-commands.md, guides/basic-use/index.md, guides/writing-addons/addon-blueprints.md, guides/writing-addons/intro-tutorial.md
RFC: https://github.com/emberjs/rfcs/pull/907
Implementation PR: https://github.com/ember-cli/ember-cli/pull/10287
Advancement: https://github.com/emberjs/rfcs/pull/932
This PR should wait to be reviewed until the implementation PR is done.
=> Add things about pnpm

guides/advanced-use/debugging.md, guides/basic-use/cli-commands.md, guides/basic-use/deploying.md, guides/writing-addons/intro-tutorial.md
We aim to teach the use of npm/yarn scripts in addition to bare CLI commands, since in real-world applications, developers may have different configurations specified in package.json scripts than the default commands would provide.
@MehulKChaudhari please review and let me know if you have any feedback!
[RFC 831](https://github.com/emberjs/rfcs/blob/master/text/0831-standardize-use-npm-yarn.md)
Since the CLI guides aim to cover the CLI behavior, I did not fully replace things like `ember serve` with `npm start`, as we may end up doing for the regular ember guides. Instead I added a little bit of prose suggesting when to use the scripts.
=> Mention npm scripts, per RFC-831
