ember-learn/cli-guides

.alexrc
guides/basic-use/deploying.md

This PR contains new content about deployments, plus copied & pasted content from the old site.

Draft content for deployments

---

app/styles/app.css

- Font color for inline code text
- Removed text decoration for the edit pencil icon

Small CSS fixes

---

guides/basic-use/cli-commands.md
guides/legacy/dependencies.md

I have some doubts about the correctness of this information. Once it's correct, I think it should be broken up and moved to other places.

rewrite dependencies

---

config/environment.js
package-lock.json
package.json

fixing edit button

---

guides/advanced-use/index.md
guides/basic-use/upgrading.md
guides/index.md

Referencing New Oxford American Dictionary and OED.

consistent spelling for backwards-compatible

---

guides/basic-use/assets-and-dependencies.md
guides/basic-use/cli-commands.md
guides/basic-use/deploying.md
guides/basic-use/index.md
guides/basic-use/upgrading.md
guides/basic-use/using-addons.md
guides/index.md

Many of these are subjective ... I'm happy to revert any of them!
These docs are a massive improvement! 🙌
(Looks like my editor is configured to strip whitespace ... I don't think that has any ramifications on markdown does it?)

various copy tweaks for consistency and clarity in "basic use"

---

guides/writing-addons/intro-tutorial.md

Fixes markdown/markdown issue called out by @levimoore in issue #34

changed markdown that should be markup

---

guides/writing-addons/intro-tutorial.md

Looks like `buttonName` should probably be `buttonLabel`.

Fix property name

---

guides/advanced-use/asset-compilation.md
guides/advanced-use/blueprints.md
guides/advanced-use/project-layouts.md
guides/advanced-use/stylesheets.md
guides/appendix/common-issues.md
guides/appendix/dev-tools.md
guides/appendix/windows.md
guides/basic-use/assets-and-dependencies.md
guides/basic-use/cli-commands.md
guides/basic-use/deploying.md
guides/basic-use/index.md
guides/basic-use/upgrading.md
guides/basic-use/using-addons.md
guides/index.md
guides/writing-addons/index.md
guides/writing-addons/intro-tutorial.md

added paths to samples, refactored for consistency

---

config/environment.js

this PR just turns off the survey prompt now that it has been closed 👍

turning off the survey

---

guides/appendix/windows.md

Per @wycats WSL can actually cause problems

Remove WSL guidance as it causes problems

---

guides/advanced-use/index.md

Would be nice to link users to official broccoli website plugins section.
Added a reference link to the same.

Update index.md with link to official site

---

guides/writing-addons/index.md

This fixes #85 
cc: @mansona @jenweber

Improves documentation of addon structure

---

guides/appendix/common-issues.md

Removes notes about Bower & fix canary instructions

---

guides/writing-addons/intro-tutorial.md

index.js within addon folder is used for exporting.

Alteration in fileName in public API sample

---

guides/appendix/dev-tools.md

ide-ember gives language service support for Atom.  It provides a lot of value.

Update dev-tools.md with Atom ide-ember

---

guides/advanced-use/project-layouts.md

Add app root files to Project Layouts

---

.local.dic
README.md
guides/pages.yml
guides/writing-addons/addon-blueprints.md
guides/writing-addons/in-repo-addons.md

Mostly a copy-paste of https://ember-cli.com/extending/#in-repo-addons, but with an extra section added in with @rwjblue's comments on dependencies from this issue: https://github.com/ember-cli/ember-cli/issues/4164

Add section on in-repo addons

---

guides/writing-addons/intro-tutorial.md

There's already a whole page on In Repo addons that covers this content well enough, I think.

Delete duplicate section on in-repo addons

---

guides/advanced-use/asset-compilation.md

cc @locks, bad proofreading on my part

Fix bad comma

---

.local.dic
guides/advanced-use/debugging.md
guides/appendix/dev-tools.md
guides/basic-use/assets-and-dependencies.md
guides/pages.yml

Closes #151
Took a stab at the content here and approached it as something useful for beginner frontend developers.

Add a page on debugging Ember CLI

---

guides/writing-addons/index.md

- Consistently use 'you' over 'we'
- Some grammatical improvements

Improve language on addon structure page

---

.local.dic
guides/basic-use/using-addons.md

Add a section on how to extend addons

---

guides/advanced-use/cli-commands-reference.md

add --lang to cli-commands-reference.md

---

.local.dic
guides/appendix/windows.md

appendix - windows - wsl2

---

guides/appendix/windows.md

I actually don't know the validity of this text because I don't have a Windows machine to test it on. I just edited the text to make it flow a bit better 👍

Improve documentation for using WSL

---

guides/appendix/windows.md

This is now very common and we should suggest it before other debugging/perf adjustments.

Recommend WSL2 for Windows users

---

guides/basic-use/cli-commands.md

doc improvement

---

guides/advanced-use/asset-compilation.md

Added online version of Autoprefixer. So users can instantly use it without installing it.

Added online version of autoprefixer.

---

guides/advanced-use/blueprints.md

- Output shows `classifiedModuleName`

Fix `camelizedModuleName` example output

---

guides/writing-addons/intro-tutorial.md

This code doesn't work unless @ is added<button>{{buttonLabel}}</button>, so fix would be <button>{{@buttonLabel}}</button>.

fix button component code in tutorial

---

guides/advanced-use/index.md

This is part of the RFC-853 work https://github.com/emberjs/rfcs/pull/960

remove mention of official support for Mocha

---

guides/basic-use/folder-layout.md

For https://github.com/emberjs/rfcs/pull/954

Remove reference to Travis
